# Generated by Django 2.0.1 on 2018-02-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='num',
            field=models.IntegerField(),
        ),
    ]
