# Generated by Django 2.0.1 on 2018-02-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdemo', '0002_auto_20180210_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysite',
            options={'ordering': ['num']},
        ),
    ]
